name: build

on:
  push:    
    paths-ignore:
    - 'README.md'
    - '.github/**'
    
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: ['9.0.x']
        
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        submodules: true
        fetch-depth: 0
        
    - name: Setup .NET ${{ matrix.version }}
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ matrix.version }}
        
    - name: Restore dependencies
      run: dotnet restore
      
    - name: MudBlazor
      run: dotnet build "ProductCatalog.MudBlazors" --no-restore
      
    - name: Build Core and Migrations only (skip WinForms on Linux)
      run: |
        dotnet build "ProductCatalog.Core" --no-restore
        dotnet build "ProductCatalog.Migrations" --no-restore

    - name: Test
      run: dotnet test "ProductCatalog.Test" --no-restore --verbosity normal
